### ISSUE TITLE
Create operator bundle and add to Operatorhub

### ISSUE THREAD

**Issue by ktenzer** [alexandrevilain/temporal-operator#121]
I would like to propose adding this operator to OperatorHub by creating the necessary manifests and building a bundle.

I have created a sample CSV here: https://gist.githubusercontent.com/ktenzer/74874e5d902d60115654c31135928314/raw/eb0dfdfbf43e4c4469bb0374d09f7cd4aa69631f/temporal-operator.clusterserviceversion.yaml

The CSV can be previewed here: https://operatorhub.io/preview

Things to do:
- I would still need to add sample spec for the namespace and client CRDs
- Add to CI/CD build process to generate bundle after building operator
- Replace current CRD endpoints ```.apps.alexandrevilain.dev``` with ```.temporal.io```
- Consider replacing k8s v1alpha1 with just v1 for Operator since the channel provides way to distinguish alpha from stable, etc which is more elegant
- Decide how to do versioning 
- Decide what channels to provide (probably just alpha for now)

**Comment by alexandrevilain** [comment]
Hi!

I rendered the preview, it's so cool ! Thanks!

> I would still need to add sample spec for the namespace and client CRDs 

Here is an example for the `TemporalNamespace`: https://github.com/alexandrevilain/temporal-operator/blob/main/examples/cluster-postgres/03-temporal-namespace.yaml
Here is an example for the `TemporalClusterClient`: https://github.com/alexandrevilain/temporal-operator/blob/main/examples/cluster-mtls/03-temporal-cluster-client.yaml

It points me to one thing: I need to improve the documentation. 

> Add to CI/CD build process to generate bundle after building operator

For sure, maybe we can find an example in an exiting repository using github actions. 

> Replace current CRD endpoints .apps.alexandrevilain.dev with .temporal.io

Yes, it seems to be mandatory to make the operator the de-facto tool to deploy a producton ready Temporal cluster on k8s. 

> Consider replacing k8s v1alpha1 with just v1 for Operator since the channel provides way to distinguish alpha from stable, etc which is more elegant
Decide how to do versioning
Decide what channels to provide (probably just alpha for now)

I don't get it. IMO we still have to follow standard k8s API versionning model. But I'm not against moving to v1. 
There is a dedicated issue for this subject: https://github.com/alexandrevilain/temporal-operator/issues/82

**Comment by ktenzer** [comment]
> I don't get it. IMO we still have to follow standard k8s API versionning model. But I'm not against moving to v1.
There is a dedicated issue for this subject: https://github.com/alexandrevilain/temporal-operator/issues/82

Yeah I didnt think about that, your right about the k8s API versioning and agree we should be consistent so I retract that point. Mostly I was talking about operator side but for starters we can just have one channel (alpha) and then go from there so maybe not something we need to decide yet.

**Comment by alexandrevilain** [comment]
Found the following example: https://github.com/jaegertracing/jaeger-operator/blob/main/Makefile#L351
It maybe a good starting point :)

**Comment by alexandrevilain** [comment]
Here is the PR: https://github.com/alexandrevilain/temporal-operator/pull/131
