### ISSUE TITLE
Remove liveness probe from worker pod

### ISSUE THREAD

**Issue by ktenzer** [alexandrevilain/temporal-operator#122]
Worker pod does not expose grpc endpoint and as such should not have liveliness probe

https://github.com/temporalio/temporal/issues/2582

**Comment by alexandrevilain** [comment]
Hi! 
Thanks for the report and the fix! 👌
I close the issue as the fix is part of release v0.6.2: https://github.com/alexandrevilain/temporal-operator/releases/tag/v0.6.2 

Thanks again, 
Alexandre!
