### ISSUE TITLE
Namespace creation through CRD isn't working

### ISSUE THREAD

**Issue by ktenzer** [alexandrevilain/temporal-operator#137]
As of latest merge namespace creation no longer works

```
Status:
  Conditions:
    Last Transition Time:  2022-09-29T00:11:18Z
    Message:               can't create "default" namespace: context deadline exceeded
    Observed Generation:   1
    Reason:                LastReconcileCycleFailed
    Status:                True
    Type:                  ReconcileError
Events:                    <none>
```

Tested from admin pod and namespace creation working.
```
# tctl namespace re
Namespace default successfully registered.
```

Also we might want to reconsider renaming CRDs. Been playing with it and because k8s has namespace object you need to reference as temporal.io.namespace. That might be confusing. 

I would propose re-consider TemporalNamespace, TemporalCluster and TemporalClusterClient. WDYT?

**Comment by alexandrevilain** [comment]
Hi!

I think it's not a bug. You ran the operator on your computer ? Or built the image and ran the operator in a deployment ? 
If you ran it in your computer, as it will try to connect to `temporal-frontend.demo:7233` it couldn't work. 

About CRD I agree for namespaces.

Maybe:
```
Cluster
TemporalNamespace
TemporalClusterClient
```
WDYT ?

**Comment by ktenzer** [comment]
Regarding the names I agree but still would favor TemporalCluster over cluster because the end user will reference cluster from cli which is generic may clash with other operator CRD forcing them to specify cluster.temporal.io. I am good either way just think it would be nicer as TemporalCluster.

**Comment by ktenzer** [comment]
Regarding namespace error, i still get same error using my EKS cluster and running operator directly. I am using this CR which reproduces issue.

<pre>
apiVersion: temporal.io/v1beta1
kind: Namespace
metadata:
  name: test
spec:
  clusterRef:
    name: prod
  description: Accounting team namespace
  retentionPeriod: 168h #7 days
</pre>

What is odd is e2e works but using CR results in no namespace created. However i also get no error in operator logs but the CR status shows deadline exceeded.

<pre>
Status:
  Conditions:
    Last Transition Time:  2022-09-29T17:27:49Z
    Message:               can't create "test" namespace: context deadline exceeded
    Observed Generation:   1
    Reason:                LastReconcileCycleFailed
    Status:                True
    Type:                  ReconcileError
</pre>

**Comment by ktenzer** [comment]
Update: after slack discussion this issue is because i am running operator locally and it doesnt have access to temporal server to create namespace.
