### ISSUE TITLE
Add Prometheus endpoint to config for server metrics scraping

### ISSUE THREAD

**Issue by ktenzer** [alexandrevilain/temporal-operator#139]
Under global params of config map we should add binding for prometheus endpoint. 

<pre>
...
  metrics:
    tags:
      type: {{ .Env.SERVICES }}
    prometheus:
      timerType: histogram
      listenAddress: "0.0.0.0:9090"
</pre>

Each service can be scrapped upon configuring.
curl http://temporaltest-frontend-headless:9090/metrics
curl http://temporaltest-history-headless:9090/metrics
curl http://temporaltest-matching-headless:9090/metrics
curl http://temporaltest-worker-headless:9090/metrics

**Comment by alexandrevilain** [comment]
Oh well found! 👍

**Comment by alexandrevilain** [comment]
Merged ;)
