### ISSUE TITLE
Add dynamicconfig client configuration to spec section

### ISSUE THREAD

**Issue by VadymBerezdetskyi** [alexandrevilain/temporal-operator#254]

**Comment by alexandrevilain** [comment]
Hi @VadymBerezdetskyi !
Thanks for the issue. Support for `dynamicconfig` looks like a really important feature missing in this Operator.
Could you please give me more context ? Like what you're trying to do, you use case ... 

I think that this issue can be a good candidate to be shipped with 0.11.0 (next release)

**Comment by VadymBerezdetskyi** [comment]
Hi! Thanks for the reply.
I'm trying to redefine dynamicconfig values to address some performance
issues regarding my temporal cluster deployment. The configmap which
defines temporal cluster config generated by operator defines
dynamicconfigClient as null and there is no option for changing this in
spec section of operator.
For now, the only available option for me is to redefine the mount which
passes my configmap instead of one generated by operator as a cluster
configuration file. Also I defined another configmap mount which represents
file with dynamicconfig values, and DYNAMICCONFIG_FILE_PASS env variable
which defines path to that file. This solution works but it's not
sophisticated.

Feel free to ask for additional details.


сб, 28 січ. 2023, 13:45 користувач Alexandre Vilain <
***@***.***> пише:

**Comment by alexandrevilain** [comment]
Hi @VadymBerezdetskyi !
The initial feature has been developed, tested and now released in v0.11.0 ! 
Feel free to test it and report any bugs or missing feature ;)
