### ISSUE TITLE
Failed ES UpdateAdvancedVisibility 

### ISSUE THREAD

**Issue by DodgeCamaro** [alexandrevilain/temporal-operator#358]
When I've tried to run temporal, I've got this erorr
`
Can't do Elasticsearch schema upgrade for no-following version numbers. (eg. from v1 to v2, but not from v1 to v3)
`
Base on temporal.io [index_template_v7.json](https://github.com/temporalio/temporal/blob/master/schema/elasticsearch/visibility/index_template_v7.json), service got v4

But, as I understand, the service doesn't have config for v4
https://github.com/alexandrevilain/temporal-operator/blob/dfeaac2787208f72aae5ca39002ff248417741a4/internal/resource/persistence/template.go#L83

**Comment by alexandrevilain** [comment]
Hi @DodgeCamaro !
Thanks for reporting this issue, you're right v4 is not supported.

PR #360 fixes it! 

I'll try to release 1.13.0 this week-end or next week. It will ship with this fix and huge reconciliation improvements. I'll ping you on this issue once done.

**Comment by alexandrevilain** [comment]
Hi @DodgeCamaro ! 
0.13.0 is now released with ES schema fix :)
