### ISSUE TITLE
Add support for Archival for backs up Workflow Execution Event Histories and Visibility data

### ISSUE THREAD

**Issue by DodgeCamaro** [alexandrevilain/temporal-operator#364]
Docs - https://docs.temporal.io/cluster-deployment-guide#set-up-archival

**Comment by DodgeCamaro** [comment]
For using archival to s3 bucket, service need to use irsa. As I know, operator don’t support overrides ServicAccount annotation

**Comment by alexandrevilain** [comment]
Thanks for the tips. Are you interested in implementing the feature ?

**Comment by DodgeCamaro** [comment]
I am interested, but I am new to Go

**Comment by alexandrevilain** [comment]
I would be really happy to review your work and help you progress with Golang :)

**Comment by DodgeCamaro** [comment]
@alexandrevilain  For store archival at s3 bucket serviceAccount needs to have annotation

https://docs.aws.amazon.com/eks/latest/userguide/associate-service-account-role.html

**Comment by alexandrevilain** [comment]
Thanks for tip! I'm trying to provide the easiest interface through the CRD to make Archival working :)

**Comment by alexandrevilain** [comment]
Hi @DodgeCamaro and @yujunz !

v0.15.0 has been released with support for archival ! Let me know if everything is working well for you!

**Comment by DodgeCamaro** [comment]
@alexandrevilain  Hi! After upgrade operator from v0.14.0 to v0.15.0
Archival doesn't enable, can fix if after recreating TemporalNamespace, but all our workflow has gone

**Comment by alexandrevilain** [comment]
Hi @DodgeCamaro!

Sorry to read that. Could you please open a new issue explaining what happened? Maybe we can fix that before you deploy 0.15.x in your production environment 👍

**Comment by yujunz** [comment]
This should have been implemented by https://github.com/alexandrevilain/temporal-operator/pull/467
