### ISSUE TITLE
Elasticsearch version supported for advanced visibility store

### ISSUE THREAD

**Issue by Tassatux** [alexandrevilain/temporal-operator#390]
Hello,

It look like the operator only support Elasticsearch version 6 or 7 for advancedVisibilityStore spec, but ES v6 support have been dropped in [Temporal 1.18](https://github.com/temporalio/temporal/releases/tag/v1.18.0) and support for ES v8 was added.

Are they plan to support Elasticsearch v8 in temporal-operator in future version?

**Comment by alexandrevilain** [comment]
Hi @Tassatux !

Thanks for reporting this issue! I did not noticed the Elasticsearch v8 support in temporal.

Looks like `v8` is just a matter of a new entry in the supported elasticsearch versions enum (see [elasticsearch client factory](https://github.com/temporalio/temporal/blob/master/common/persistence/visibility/store/elasticsearch/client/client_factory.go#L36)).

As a workaround did you tried setting `v7` in the `TemporalCluster` CR pointing to your ESv8 cluster ?

I'll try to add support for `v8` as soon as possible. If you have free time don't hestitate to contribute, I'll be really happy to review your Pull Request.

**Comment by Tassatux** [comment]
Oh indeed, with v7 in spec and targeting an ES v8 cluster it work. I had problem previously and assumed there may be something incompatible, but this was a bug for ES schema v4 migration fixed in v0.13.0.
