### ISSUE TITLE
Add support for Temporal 1.21.x

### ISSUE THREAD

**Issue by alexandrevilain** [alexandrevilain/temporal-operator#395]

**Comment by yujunz** [comment]
Is there a brief developer guide for adding support for temporal new releases?

**Comment by alexandrevilain** [comment]
Hi! There is no particular guide. I look at the changelog and I implement required features to make the operator compatible with 1.21. 

I'll try to add support for 1.21 this week.

**Comment by alexandrevilain** [comment]
According to: https://github.com/temporalio/temporal/releases/tag/v1.21.0
There are no big change to do in the operator to support 1.21.x:
- Worker versionning is enabled using dynamic config: already supported
- Synchronous Updates are only API changes
- Batch Reset via BatchOperation API are only API changes
- Dynamic rate limiter is enabled using dynamic config: already supported
- Updated defaultAuthorizer and defaultJWTClaimMapper: not supported for now by the operator
- Visibility depreciations: requires some webhook warning to inform users about the new config and maybe API update. Will check that.
- List and Scan APIs are only API changes
- Frontend Service shutdown behavior as the behavior changes, I need to check that
- Dynamic config validation: The webhook can ensure that datas will be ok for dynamic config
- Per workflow limit are only API changes
+ 1.21.0 and 1.21.1 are broken, the webhook should prevent upgrading to those versions.


Here is the todo list for this issue:

- [ ]  Allow 1.21.x version upgrade
- [ ]  Add check in webhook to disable upgrades to 1.21.0 and 1.21.1 which are broken (see notice on: https://github.com/temporalio/temporal/releases/tag/v1.21.0)
- [ ] Add dynamic config pre-validation in the webhook
- [ ] Support new frontend shutdown behavior
- [ ] Prepare API and webhook for upcoming visibility depreciations

**Comment by alexandrevilain** [comment]
Released in 0.14.0
