### ISSUE TITLE
arm64 temporal-operator

### ISSUE THREAD

**Issue by abratanich** [alexandrevilain/temporal-operator#434]
Please add the architecture arm64 image ghcr.io/alexandrevilain/temporal-operator. This will greatly increase versatility. Thank you

**Comment by alexandrevilain** [comment]
Good idea! 

New kubebuilder projects are coming with the "docker-buildx" make target which does the job.
See: https://github.com/kubernetes-sigs/kubebuilder/blob/master/testdata/project-v4/Makefile#L96 

We have to take this for this feature and update the github workflow accordingly.

**Comment by abratanich** [comment]
Can I count on arm64 additions because my entire project is on arm ?

**Comment by alexandrevilain** [comment]
Hi @abratanich ! Image for v0.15.0 is available for linux/arm64 :)
