### ISSUE TITLE
Helm chart

### ISSUE THREAD

**Issue by ganievs** [alexandrevilain/temporal-operator#436]
Hi @alexandrevilain! First of all, I come to say you've done great work!
I made a test setup of the operator and would like to use it as the main way to manage our Temporal clusters in the future and it would be great if the operator will have the ability to install it through the helm.

**Comment by ganievs** [comment]
I've prepared PR #437 with a chart generation. Would be great if you add it to your release pipeline.

**Comment by alexandrevilain** [comment]
Thanks for your contribution!
That's a really great idea!
Don't you think it could be better to run the helmify command only one time and push the first version of the helm chart in the PR ?

Then we'll have to:

- update the "prepare-release" target to update helm chart
- find a way to host charts maybe using github pages
- update the release workflow to push the helm chart for each new releases.
What do you think ?

**Comment by ganievs** [comment]
I think the best option is to use https://github.com/helm/chart-releaser-action as starting point.
The final release action will look like [that](https://gist.github.com/ganievs/8723d67d14f6709d7924df4dcf181cfe)
But you already have a static site on the operator repo, so might be good to set up publishing in another repo

**Comment by ganievs** [comment]
Also, a possible way is to push the chart package to GitHub's package registry.

Here is an example from my fork repo:
> Chart publication
```bash
$ make helm 
$ helm package charts/temporal-operator
$ helm registry login ghcr.io --username ganievs
$ helm push ./temporal-operator-0.1.0.tgz oci://ghcr.io/ganievs/temporal-operator
```
> Chart installation
```bash
$ helm template temporal-operator oci://ghcr.io/ganievs/temporal-operator/temporal-operator --version 0.1.0
$ helm install temporal-operator  oci://ghcr.io/ganievs/temporal-operator/temporal-operator --version 0.1.0
```

**Comment by alexandrevilain** [comment]
Good idea! 
Pushing the chart as oci artifact is IMO the best option! 

> Don't you think it could be better to run the helmify command only one time and push the first version of the helm chart in the PR ?`

Don't you want to update the pull request with my previous comment ? Then we could add the chart to the oci repo ! 

Thanks again for your work 👍

**Comment by ganievs** [comment]
Ok, will do

**Comment by ganievs** [comment]
Hi @alexandrevilain! So, I rebased from the main and add pushed generated chart in the PR.

**Comment by alexandrevilain** [comment]
Cool! Thanks @ganievs ! I'll take time to carefully review it after the 0.15.0 release.
Looks like the generated `values.yaml` is a little bit complicated, IMO the `controllerManager.manager` it too much. 
I like simpler formats like cert-manager: https://github.com/cert-manager/cert-manager/blob/master/deploy/charts/cert-manager/values.yaml

But I'll try provide valuable comments on the PR  👍

**Comment by alexandrevilain** [comment]
Now that:
- https://github.com/alexandrevilain/temporal-operator/pull/592
- https://github.com/alexandrevilain/temporal-operator/pull/437 
Are merged, closing.
