### ISSUE TITLE
Does Temporal Support containerd at AWS EKS 1.24?

### ISSUE THREAD

**Issue by DodgeCamaro** [alexandrevilain/temporal-operator#440]
Due this [doc](https://docs.aws.amazon.com/eks/latest/userguide/dockershim-deprecation.html),  Dockershim was deprecated.
Does Temporal support running of containerd as a container-runtime?

**Comment by alexandrevilain** [comment]
Hi!
Yes no issue, I'm running it in production with containerd.

**Comment by DodgeCamaro** [comment]
Good, thank you!
