### ISSUE TITLE
Warning on immutable values

### ISSUE THREAD

**Issue by yujunz** [alexandrevilain/temporal-operator#444]
The operator should warn user when modifying immutable values. e.g.

> numHistoryShards
> Required - The number of history shards to create when initializing the Cluster.
> 
> Warning: This value is immutable and will be ignored after the first run. Please ensure you set this value appropriately high enough to scale with the worst case peak load for this Cluster.

https://docs.temporal.io/references/configuration#numhistoryshards

**Comment by alexandrevilain** [comment]
Hi!

It looks like a regression, the operator was ensuring the number of shard were not updated. 

I’ll look at this asap, thanks!
