### ISSUE TITLE
Operator don't add archival after update from 0.14.0 to 0.15.0

### ISSUE THREAD

**Issue by DodgeCamaro** [alexandrevilain/temporal-operator#449]
I've faced with a bug, after migrating temporal-operator from 0.14.0 to 0.15.0. TemporalNamespace doesn't upgrade when I've added archival config on the existing temporal. When I created temporal from zero, it's worked well.

**Comment by alexandrevilain** [comment]
Hi @DodgeCamaro ! 
Ok I think this issue is due to deployment not rolled out after config is updated. I'll try to fix this ASAP! 
Thanks for reporting the issue!
