### ISSUE TITLE
How enable debug mode?

### ISSUE THREAD

**Issue by DodgeCamaro** [alexandrevilain/temporal-operator#452]
I need to debug connection between AWS Opensearch and temporal-worker
How I can enable debug?

**Comment by alexandrevilain** [comment]
Hi @DodgeCamaro !
Thanks for the issue! The temporal server log config is not available using the operator! This could be a good addition without requiring so much work!

**Comment by yujunz** [comment]
Can it be modified manually but not being reverted by the controller during reconciliation?

It seems another use case for https://github.com/alexandrevilain/temporal-operator/issues/418
