### ISSUE TITLE
Invalid link to cert-manager image

### ISSUE THREAD

**Issue by yujunz** [alexandrevilain/temporal-operator#471]
https://alexandrevilain.github.io/temporal-operator/features/mtls/cert-manager/

![Screenshot 2023-08-22 at 14 43 51](https://github.com/alexandrevilain/temporal-operator/assets/6813397/31498505-e0c0-419a-9422-6d77e0601c8d)

The image url `https://alexandrevilain.github.io/assets/mtls-certmanager.png` should be `https://alexandrevilain.github.io/temporal-operator/assets/mtls-certmanager.png`

**Comment by yujunz** [comment]
I thought it has been fixed by https://github.com/alexandrevilain/temporal-operator/pull/417 but seems not effective.

**Comment by alexandrevilain** [comment]
Hey :) 

Now that site is deployed on clouflare pages, it works well, see: https://temporal-operator.pages.dev/features/mtls/cert-manager/
