### ISSUE TITLE
Support temporal 1.22.x

### ISSUE THREAD

**Issue by yujunz** [alexandrevilain/temporal-operator#502]
Branch: https://github.com/temporalio/temporal/tree/release/v1.22.x
Tag: https://github.com/temporalio/temporal/releases/tag/v1.22.0

Not sure how much effort it takes to support a new minor version. If there is a brief developer guide, more contributors may help if needed.

**Comment by alexandrevilain** [comment]
Hi!

Looks like we'll only need to add a new API field for frontend http support.
It should not take too many time.
