### ISSUE TITLE
How to set `authorization` config?

### ISSUE THREAD

**Issue by smndtrl** [alexandrevilain/temporal-operator#538]
Hi,

I wasn't able to find out how to set the `authorization` settings. It seems the `configmap` generated always leaves them empty. As the configis not dynamically created the same way it happens in the `temporalio/server` docker, setting env vars on the worker service using overrides was also not successful.

Am I missing something obvious?

**Comment by alexandrevilain** [comment]
Hi @smndtrl !

Thanks for filling the issue. You're right, the `authorization` setting is missing in the `TemporalCluster` CR. 

I'll add this for the next release (`v0.16.0`).
