### ISSUE TITLE
temporal cli commands do not work when mTLS is enabled

### ISSUE THREAD

**Issue by vinimona** [alexandrevilain/temporal-operator#546]
I created a mTLS enabled temporal cluster (using cert-manager) and observed that 'temporal operator namespace list' or any temporal cli command doesn't work from admintools. This also leads to the problem that temporal namespaces are not registered using the TemporalNamespace CRD.

> $ temporal operator namespace list
> Error: unable to list namespaces: connection error: desc = "error reading server preface: EOF"
> ('export TEMPORAL_CLI_SHOW_STACKS=1' to see stack traces)

Please note that the 'tctl' commands still work. It appears the TEMPORAL_TLS_* env variables in admintools container are not set.

**Comment by alexandrevilain** [comment]
Thanks for your report @vinimona !
I was able to reproduce and fix the issue in #547.

This fix will part of 0.16.0
