### ISSUE TITLE
Does temporal-operator support overrides nodeSelector ?

### ISSUE THREAD

**Issue by Aoao54** [alexandrevilain/temporal-operator#563]
Got error with the config below. 

    overrides:
      deployment:
        spec:
          template:
            nodeSelector:
              server-type: cpu
              service: services

> error validating data:ValidationError(TemporalCluster.spec.services.overrides.deployment.spec.template): unknownfield "nodeSelector" in io.temporal.v1beta1.TemporalCluster.spec.services.overrides.deployment.spec.template

It seems like temporal-operator doesn't support it now.

**Comment by yujunz** [comment]
I thought the override spec inherit the Kubernetes schema. It turns out not so?

**Comment by alexandrevilain** [comment]
Hi @Aoao54, @yujunz 

I think the override you provided is wrong, because `nodeSelector` is available in `deployment.spec.template.spec.nodeSelector`. 

It should work if you add the missing `spec`. Could you please try ?

**Comment by alexandrevilain** [comment]
> I also noticed the overrides separates meta from spec on purpose. What was the reason behind it? Why not just use the full spec?

I wanted to let user customize some values in meta like labels and annotations, but not others like name or namespace which could break things.

**Comment by Aoao54** [comment]
Succeed. It's a typo mistake. Thanks guys !
