### ISSUE TITLE
Does operator support changing the value of Config.global.metrics.perUnitHistogramBoundaries ?

### ISSUE THREAD

**Issue by Aoao54** [alexandrevilain/temporal-operator#565]
For now, the default bucket sizes of some metrics did not align with the default limit sizes. Such as the default threshold of history_size_error is 50MB but the default max bucket sizes is 16MB.
This could be used to change the the default bucket sizes and set alerts for those metrics which can be customized in temporal dynamic config like below. 

<img width="1219" alt="image" src="https://github.com/alexandrevilain/temporal-operator/assets/84021683/2df36773-58ce-4732-b546-1577355ad573">

**Comment by Aoao54** [comment]
Just checked the code , looks like it's not supported. I'll raise a PR about it. If no one is oppose  : )

**Comment by alexandrevilain** [comment]
> I'll raise a PR about it. If no one opposes : )

Feel *always* free to raise a PR :)

**Comment by yujunz** [comment]
Digging a bit into the code, it seems `Config.global.metrics.perUnitHistogramBoundaries` is defined in temporal as below

https://github.com/temporalio/temporal/blob/893a8f3d51567f889dd6e7f973196f7d94bb1cbe/common/config/config.go#L112
```
	Global struct {
...
		// Metrics is the metrics subsystem configuration
		Metrics *metrics.Config `yaml:"metrics"`
	}
```

https://github.com/temporalio/temporal/blob/893a8f3d51567f889dd6e7f973196f7d94bb1cbe/common/metrics/config.go#L75

```go
	Config struct {
		ClientConfig `yaml:"clientConfig,inline"`
...
	}

	ClientConfig struct {
		Tags map[string]string `yaml:"tags"`
		ExcludeTags map[string][]string `yaml:"excludeTags"`
		Prefix string `yaml:"prefix"`
		PerUnitHistogramBoundaries map[string][]float64 `yaml:"perUnitHistogramBoundaries"`
	}
```

Mapping to what is supported by the operator

https://github.com/alexandrevilain/temporal-operator/blob/e6b742ad358a11defb108d383a6e90180f8fbcf6/internal/resource/config/configmap_builder.go#L311

```
	if b.instance.Spec.Metrics.IsEnabled() {
		temporalCfg.Global.Metrics = &metrics.Config{
			ClientConfig: metrics.ClientConfig{
				Tags: map[string]string{"type": "{{ .Env.SERVICES }}"},
			},
		}
...
	}
```

It seems it only generates the tags but not the others like `perUnitHistogramBoundarie` in this case. We can surely patch it easily in the configmap builder.

But what if someone wants to define `excludedTags`? Do we need another patch?

Maybe abusing the [overrides](https://alexandrevilain.github.io/temporal-operator/features/overrides/) to mount an external configmap can be a workaround but that is likely overriding all parameters from cluster spec for config. This may not be a desired behavior. Config content is harder to patch than other structured resources.

I wonder if there is a generic solution for such use case. Maybe introducing an pluggable config map generator so we can define the config without hardcoding the logic in binary. It might be overkilled for this simple use case but could be something to consider for v1.0 milestone or v2.0 roadmap.  What do you think? @alexandrevilain
