### ISSUE TITLE
Publishing to operatorhub.io has stopped

### ISSUE THREAD

**Issue by bs1180** [alexandrevilain/temporal-operator#568]
Hi,
The last version published to OperatorHub is [0.12](https://github.com/k8s-operatorhub/community-operators/tree/main/operators/temporal-operator) - can this get updated? I see there is a prewritten script to make the PR, so I can also do it if you'd prefer a community approach? 

Thanks!

**Comment by alexandrevilain** [comment]
Hi! 

For sure you can easily contribute to this by running: `make operatorhub`.

For instance:

```bash
git clone https://github.com/alexandrevilain/temporal-operator.git
cd temporal-operator
git checkout v0.16.2
make operatorhub
```

**Comment by alexandrevilain** [comment]
Just published 0.16.0: https://github.com/k8s-operatorhub/community-operators/pull/3710
Will do for 0.16.1 and 0.16.2

**Comment by alexandrevilain** [comment]
I have to start by 0.12.2: https://github.com/k8s-operatorhub/community-operators/pull/3711
Then I'll do the next version:
0.13.x
0.14.x
0.15.x
0.16.x

Will take some time, sorry

**Comment by alexandrevilain** [comment]
Done for:
0.12.2: https://github.com/k8s-operatorhub/community-operators/pull/3711
0.13.0: https://github.com/k8s-operatorhub/community-operators/pull/3712
0.13.1: https://github.com/k8s-operatorhub/community-operators/pull/3713
0.13.2: https://github.com/k8s-operatorhub/community-operators/pull/3714
0.13.3: https://github.com/k8s-operatorhub/community-operators/pull/3715

Starting 0.14.0 ..

**Comment by alexandrevilain** [comment]
0.14.0: https://github.com/k8s-operatorhub/community-operators/pull/3716
0.15.0: https://github.com/k8s-operatorhub/community-operators/pull/3718
0.15.1: https://github.com/k8s-operatorhub/community-operators/pull/3723
0.15.2: https://github.com/k8s-operatorhub/community-operators/pull/3724 
0.15.3: https://github.com/k8s-operatorhub/community-operators/pull/3725
0.15.4: https://github.com/k8s-operatorhub/community-operators/pull/3726

Starting 0.16.0 ...

**Comment by alexandrevilain** [comment]
0.16.0: https://github.com/k8s-operatorhub/community-operators/pull/3728
0.16.1: https://github.com/k8s-operatorhub/community-operators/pull/3729
0.16.2: https://github.com/k8s-operatorhub/community-operators/pull/3731

Finished ! 🎉
