### ISSUE TITLE
Defining a storage class on S3 archival

### ISSUE THREAD

**Issue by frucher08** [alexandrevilain/temporal-operator#604]
Hi, I was wondering if it is possible to define the storage class to use for S3 archive to be STANDARD_IA.
Thanks!

**Comment by alexandrevilain** [comment]
Hi @frucher08 !

I don't think this is even possibile in Temporal, see available configuration: https://github.com/temporalio/temporal/blob/v1.22.3/common/config/config.go#L491

When available in Temporal itself, I would be able to add support for S3 IA in the operator.
