### ISSUE TITLE
TemporalWorkerProcess API deprecation

### ISSUE THREAD

**Issue by alexandrevilain** [alexandrevilain/temporal-operator#621]
After some times without improving TemporalWorkerProcess (see #205), I don't see any user traction for this API.

The only real value for `TemporalWorkerProcess` was automatic mTLS using cert-manager. This is still doable with `TemporalClusterClient` and `Deployment`. 

I create this issue to start `TemporalWorkerProcess` API depreciation. 

Here is the schedule I'll try to apply:
- Deprecation notice in `0.17.0`
- If no one is asking for help to migrate, remove the API in `0.18.0`

After creating this issue, I will close:
- #205 
- #269

**Comment by s123121** [comment]
Can you give ETA for 0.18.0 ? I decided to jump into temporal operator for my new project, but see the depreciation notice so have to put it on hold

**Comment by s123121** [comment]
can you give ETA for 0.18.0? I am noob both of temporal & k8s so the first thing I do is checking out the `example` for any operator.

**Comment by alexandrevilain** [comment]
Maybe next week.
