### ISSUE TITLE
cassandra schema version compatibility check failed: no connections were made when creating the session

### ISSUE THREAD

**Issue by j0hnni3** [alexandrevilain/temporal-operator#659]
Hi @alexandrevilain!

Unfortunately, I ran into a problem when deploying a temporal cluster
I am trying to install a temporal cluster + cassandra on k8s using the operator.

**What steps did you take and what happened:**
1. I am installing CRD + temporal operator, by link from - https://temporal-operator.pages.dev/getting-started/
2. Then I use this example to deploy the configurations used by the temporal-cluster from
https://github.com/alexandrevilain/temporal-operator/tree/main/examples/cluster-cassandra

The installation process is successfully completed by installing **cassandra** and **prod-schema-scripts**.
After that, the temporal services will start, but not all of them.

**Successfully launched**:
<details>
<summary> prod-create-visibility-database-9vgx7</summary>

>     2024-03-18T17:40:18.918Z	INFO	Validating connection to cassandra cluster.	{"logging-call-at": "cqlclient.go:110"}
>     2024-03-18T17:40:18.957Z	INFO	Connection validation succeeded.	{"logging-call-at": "cqlclient.go:116"}
>     2024-03-18T17:40:18.957Z	INFO	Creating Keyspace temporal_visibility using SimpleStrategy with RF=1.	{"logging-call-at": "cqlclient.go:163"}
</details>

<details>
  <summary>prod-setup-default-schema-mqx8t </summary>

>       2024-03-18T17:40:28.950Z	INFO	Validating connection to cassandra cluster.	{"logging-call-at": "cqlclient.go:110"}
>       2024-03-18T17:40:28.985Z	INFO	Connection validation succeeded.	{"logging-call-at": "cqlclient.go:116"}
>       2024-03-18T17:40:28.986Z	INFO	Starting schema setup	{"config": {"SchemaFilePath":"","InitialVersion":"0.0","Overwrite":false,"DisableVersioning":false}, "logging-call-at": "setuptask.go:58"}
>       2024-03-18T17:40:28.986Z	DEBUG	Setting up version tables	{"logging-call-at": "setuptask.go:68"}
>       2024-03-18T17:40:29.158Z	DEBUG	Setting initial schema version to 0.0	{"logging-call-at": "setuptask.go:119"}
>       2024-03-18T17:40:29.165Z	DEBUG	Updating schema update log	{"logging-call-at": "setuptask.go:124"}
>       2024-03-18T17:40:29.174Z	INFO	Schema setup complete	{"logging-call-at": "setuptask.go:132"}

</details>

<details>
  <summary>prod-setup-visibility-schema-t29zg </summary>

>       2024-03-18T17:40:39.081Z	INFO	Validating connection to cassandra cluster.	{"logging-call-at": "cqlclient.go:110"}
>       2024-03-18T17:40:39.119Z	INFO	Connection validation succeeded.	{"logging-call-at": "cqlclient.go:116"}
>       2024-03-18T17:40:39.119Z	INFO	Starting schema setup	{"config": {"SchemaFilePath":"","InitialVersion":"0.0","Overwrite":false,"DisableVersioning":false}, "logging-call-at": "setuptask.go:58"}
>       2024-03-18T17:40:39.119Z	DEBUG	Setting up version tables	{"logging-call-at": "setuptask.go:68"}
>       2024-03-18T17:40:39.355Z	DEBUG	Setting initial schema version to 0.0	{"logging-call-at": "setuptask.go:119"}
>       2024-03-18T17:40:39.363Z	DEBUG	Updating schema update log	{"logging-call-at": "setuptask.go:124"}
>       2024-03-18T17:40:39.372Z	INFO	Schema setup complete	{"logging-call-at": "setuptask.go:132"}  

</details>

<details>
  <summary>prod-update-default-schema-v-1-20-0-rhcx9 </summary>

>       2024-03-18T17:40:49.024Z	INFO	Validating connection to cassandra cluster.	{"logging-call-at": "cqlclient.go:110"}
>       2024-03-18T17:40:49.058Z	INFO	Connection validation succeeded.	{"logging-call-at": "cqlclient.go:116"}
>       2024-03-18T17:40:49.058Z	INFO	UpdateSchemeTask started	{"config": {"DBName":"","TargetVersion":"","SchemaDir":"/etc/temporal/schema/cassandra/temporal/versioned","IsDryRun":false}, "logging-call-at": "updatetask.go:98"}
>       2024-03-18T17:40:49.065Z	DEBUG	Schema Dirs: [v1.0 v1.1 v1.2 v1.3 v1.4 v1.5 v1.6 v1.7]	{"logging-call-at": "updatetask.go:187"}
>       2024-03-18T17:40:49.065Z	INFO	Processing schema file: /etc/temporal/schema/cassandra/temporal/versioned/v1.0/schema.cql	{"logging-call-at": "updatetask.go:233"}
>       2024-03-18T17:40:49.065Z	INFO	Processing schema file: /etc/temporal/schema/cassandra/temporal/versioned/v1.1/cluster_metadata.cql	{"logging-call-at": "updatetask.go:233"}
>       2024-03-18T17:40:49.065Z	INFO	Processing schema file: /etc/temporal/schema/cassandra/temporal/versioned/v1.2/queue.cql	{"logging-call-at": "updatetask.go:233"}
>       2024-03-18T17:40:49.065Z	INFO	Processing schema file: /etc/temporal/schema/cassandra/temporal/versioned/v1.3/visibility.cql	{"logging-call-at": "updatetask.go:233"}
>       2024-03-18T17:40:49.065Z	INFO	Processing schema file: /etc/temporal/schema/cassandra/temporal/versioned/v1.4/executions.cql	{"logging-call-at": "updatetask.go:233"}
>       2024-03-18T17:40:49.065Z	INFO	Processing schema file: /etc/temporal/schema/cassandra/temporal/versioned/v1.4/cluster_metadata.cql	{"logging-call-at": "updatetask.go:233"}
>       2024-03-18T17:40:49.065Z	INFO	Processing schema file: /etc/temporal/schema/cassandra/temporal/versioned/v1.5/event.cql	{"logging-call-at": "updatetask.go:233"}
>       2024-03-18T17:40:49.066Z	INFO	Processing schema file: /etc/temporal/schema/cassandra/temporal/versioned/v1.5/executions.cql	{"logging-call-at": "updatetask.go:233"}
>       2024-03-18T17:40:49.066Z	INFO	Processing schema file: /etc/temporal/schema/cassandra/temporal/versioned/v1.6/executions.cql	{"logging-call-at": "updatetask.go:233"}
>       2024-03-18T17:40:49.066Z	INFO	Processing schema file: /etc/temporal/schema/cassandra/temporal/versioned/v1.6/cluster_metadata_info.cql	{"logging-call-at": "updatetask.go:233"}
>       2024-03-18T17:40:49.066Z	INFO	Processing schema file: /etc/temporal/schema/cassandra/temporal/versioned/v1.7/executions.cql	{"logging-call-at": "updatetask.go:233"}
>       2024-03-18T17:40:49.066Z	DEBUG	---- Executing updates for version 1.0 ----	{"logging-call-at": "updatetask.go:151"}
>       2024-03-18T17:40:49.066Z	DEBUG	CREATE TYPE serialized_event_batch ( encoding_type text, version int, data blob );	{"logging-call-at": "updatetask.go:153"}
>       2024-03-18T17:40:49.118Z	DEBUG	CREATE TABLE executions ( shard_id int, type int, namespace_id uuid, workflow_id text, run_id uuid, current_run_id uuid, visibility_ts timestamp, task_id bigint, shard blob, shard_encoding text, execution blob, execution_encoding text, execution_state blob, execution_state_encoding text, transfer blob, transfer_encoding text, replication blob, replication_encoding text, timer blob, timer_encoding text, next_event_id bigint, range_id bigint, activity_map map<bigint, blob>, activity_map_encoding text, timer_map map<text, blob>, timer_map_encoding text, child_executions_map map<bigint, blob>, child_executions_map_encoding text, request_cancel_map map<bigint, blob>, request_cancel_map_encoding text, signal_map map<bigint, blob>, signal_map_encoding text, signal_requested set<uuid>, buffered_events_list list<frozen<serialized_event_batch>>, replication_metadata blob, replication_metadata_encoding text, workflow_last_write_version bigint, workflow_state int, checksum blob, checksum_encoding text, PRIMARY KEY (shard_id, type, namespace_id, workflow_id, run_id, visibility_ts, task_id) ) WITH COMPACTION = { 'class': 'org.apache.cassandra.db.compaction.LeveledCompactionStrategy' };	{"logging-call-at": "updatetask.go:153"}
>       2024-03-18T17:40:49.191Z	DEBUG	CREATE TABLE history_node ( tree_id uuid, branch_id uuid, node_id bigint, txn_id bigint, data blob, data_encoding text, PRIMARY KEY ((tree_id), branch_id, node_id, txn_id ) ) WITH CLUSTERING ORDER BY (branch_id ASC, node_id ASC, txn_id DESC) AND COMPACTION = { 'class': 'org.apache.cassandra.db.compaction.LeveledCompactionStrategy' };	{"logging-call-at": "updatetask.go:153"}
>       2024-03-18T17:40:49.285Z	DEBUG	CREATE TABLE history_tree ( tree_id uuid, branch_id uuid, branch blob, branch_encoding text, PRIMARY KEY ((tree_id), branch_id ) ) WITH COMPACTION = { 'class': 'org.apache.cassandra.db.compaction.LeveledCompactionStrategy' };	{"logging-call-at": "updatetask.go:153"}
>       2024-03-18T17:40:49.382Z	DEBUG	CREATE TABLE tasks ( namespace_id uuid, task_queue_name text, task_queue_type int, type int, task_id bigint, range_id bigint, task blob, task_encoding text, task_queue blob, task_queue_encoding text, PRIMARY KEY ((namespace_id, task_queue_name, task_queue_type), type, task_id) ) WITH COMPACTION = { 'class': 'org.apache.cassandra.db.compaction.LeveledCompactionStrategy' };	{"logging-call-at": "updatetask.go:153"}

</details>

<details>
  <summary> prod-update-visibility-schema-v-1-20-0-cass-zfdk5</summary>

>       2024-03-18T17:40:59.069Z	INFO	Validating connection to cassandra cluster.	{"logging-call-at": "cqlclient.go:110"}
>       2024-03-18T17:40:59.103Z	INFO	Connection validation succeeded.	{"logging-call-at": "cqlclient.go:116"}
>       2024-03-18T17:40:59.103Z	INFO	UpdateSchemeTask started	{"config": {"DBName":"","TargetVersion":"","SchemaDir":"/etc/temporal/schema/cassandra/visibility/versioned","IsDryRun":false}, "logging-call-at": "updatetask.go:98"}
>       2024-03-18T17:40:59.109Z	DEBUG	Schema Dirs: [v1.0]	{"logging-call-at": "updatetask.go:187"}
>       2024-03-18T17:40:59.109Z	INFO	Processing schema file: /etc/temporal/schema/cassandra/visibility/versioned/v1.0/schema.cql	{"logging-call-at": "updatetask.go:233"}
>       2024-03-18T17:40:59.109Z	DEBUG	---- Executing updates for version 1.0 ----	{"logging-call-at": "updatetask.go:151"}
>       2024-03-18T17:40:59.109Z	DEBUG	CREATE TABLE open_executions ( namespace_id uuid, namespace_partition int, workflow_id text, run_id uuid, start_time timestamp, execution_time timestamp, workflow_type_name text, memo blob, encoding text, task_queue text, PRIMARY KEY ((namespace_id, namespace_partition), start_time, run_id) ) WITH CLUSTERING ORDER BY (start_time DESC) AND COMPACTION = { 'class': 'org.apache.cassandra.db.compaction.LeveledCompactionStrategy', 'tombstone_threshold': 0.4 } AND GC_GRACE_SECONDS = 60;	{"logging-call-at": "updatetask.go:153"}
>       2024-03-18T17:40:59.165Z	DEBUG	CREATE INDEX open_by_workflow_id ON open_executions (workflow_id);	{"logging-call-at": "updatetask.go:153"}
>       2024-03-18T17:40:59.250Z	DEBUG	CREATE INDEX open_by_type ON open_executions (workflow_type_name);	{"logging-call-at": "updatetask.go:153"}
>       2024-03-18T17:40:59.299Z	DEBUG	CREATE TABLE closed_executions ( namespace_id uuid, namespace_partition int, workflow_id text, run_id uuid, start_time timestamp, execution_time timestamp, close_time timestamp, status int, workflow_type_name text, history_length bigint, memo blob, encoding text, task_queue text, PRIMARY KEY ((namespace_id, namespace_partition), close_time, run_id) ) WITH CLUSTERING ORDER BY (close_time DESC) AND COMPACTION = { 'class': 'org.apache.cassandra.db.compaction.LeveledCompactionStrategy' } AND GC_GRACE_SECONDS = 172800;	{"logging-call-at": "updatetask.go:153"}
>       2024-03-18T17:40:59.346Z	DEBUG	CREATE INDEX closed_by_workflow_id ON closed_executions (workflow_id);	{"logging-call-at": "updatetask.go:153"}
>       2024-03-18T17:40:59.409Z	DEBUG	CREATE INDEX closed_by_close_time ON closed_executions (close_time);	{"logging-call-at": "updatetask.go:153"}
>       2024-03-18T17:40:59.467Z	DEBUG	CREATE INDEX closed_by_type ON closed_executions (workflow_type_name);	{"logging-call-at": "updatetask.go:153"}
>       2024-03-18T17:40:59.519Z	DEBUG	CREATE INDEX closed_by_status ON closed_executions (status);	{"logging-call-at": "updatetask.go:153"}
>       2024-03-18T17:40:59.586Z	DEBUG	---- Done ----	{"logging-call-at": "updatetask.go:159"}
>       2024-03-18T17:40:59.599Z	DEBUG	Schema updated from 0.0 to 1.0	{"logging-call-at": "updatetask.go:143"}
>       2024-03-18T17:40:59.599Z	INFO	UpdateSchemeTask done	{"logging-call-at": "updatetask.go:121"}

</details>

Also, ReplicaSet for the UI and Admintools runs correctly

**Components are not running**
Frontend, history, matching, and worker services did not start with errors
```
cassandra schema version compatibility check failed: no connections were made when creating the session
Unable to create server.
```

<details>
  <summary> prod-worker-5dcf7cdccf-jgkt9</summary>

>        TEMPORAL_CLI_ADDRESS is not set, setting it to 10.244.0.31:7233
>       2024/03/18 17:52:28 Loading config; env=docker,zone=,configDir=config
>       2024/03/18 17:52:28 Loading config files=[config/docker.yaml]
>       {"level":"info","ts":"2024-03-18T17:52:28.274Z","msg":"Build info.","git-time":"2023-02-17T00:53:28.000Z","git-revision":"b313b7f586415f98dde332c6b4d1801e48b187a4","git-modified":false,"go-arch":"arm64","go-os":"linux","go-version":"go1.19.5","cgo-enabled":false,"server-version":"1.20.0","debug-mode":false,"logging-call-at":"main.go:143"}
>       {"level":"info","ts":"2024-03-18T17:52:28.274Z","msg":"Dynamic config client is not configured. Using noop client.","logging-call-at":"main.go:163"}
>       {"level":"warn","ts":"2024-03-18T17:52:28.274Z","msg":"Not using any authorizer and flag `--allow-no-auth` not detected. Future versions will require using the flag `--allow-no-auth` if you do not want to set an authorizer.","logging-call-at":"main.go:173"}
>       [Fx] PROVIDE	*pprof.PProfInitializerImpl <= go.temporal.io/server/common/pprof.NewInitializer()
>       [Fx] PROVIDE	*temporal.ServerImpl <= go.temporal.io/server/temporal.NewServerFxImpl()
>       [Fx] PROVIDE	temporal.Server <= go.temporal.io/server/temporal.glob..func9()
>       [Fx] SUPPLY	[]temporal.ServerOption
>       [Fx] PROVIDE	*temporal.serverOptions <= go.temporal.io/server/temporal.ServerOptionsProvider()
>       [Fx] PROVIDE	chan interface {} <= go.temporal.io/server/temporal.ServerOptionsProvider()
>       [Fx] PROVIDE	*config.Config <= go.temporal.io/server/temporal.ServerOptionsProvider()
>       [Fx] PROVIDE	*config.PProf <= go.temporal.io/server/temporal.ServerOptionsProvider()
>       [Fx] PROVIDE	log.Config <= go.temporal.io/server/temporal.ServerOptionsProvider()
>       [Fx] PROVIDE	resource.ServiceNames <= go.temporal.io/server/temporal.ServerOptionsProvider()
>       [Fx] PROVIDE	resource.NamespaceLogger <= go.temporal.io/server/temporal.ServerOptionsProvider()
>       [Fx] PROVIDE	resolver.ServiceResolver <= go.temporal.io/server/temporal.ServerOptionsProvider()
>       [Fx] PROVIDE	client.AbstractDataStoreFactory <= go.temporal.io/server/temporal.ServerOptionsProvider()
>       [Fx] PROVIDE	searchattribute.Mapper <= go.temporal.io/server/temporal.ServerOptionsProvider()
>       [Fx] PROVIDE	[]grpc.UnaryServerInterceptor <= go.temporal.io/server/temporal.ServerOptionsProvider()
>       [Fx] PROVIDE	authorization.Authorizer <= go.temporal.io/server/temporal.ServerOptionsProvider()
>       [Fx] PROVIDE	authorization.ClaimMapper <= go.temporal.io/server/temporal.ServerOptionsProvider()
>       [Fx] PROVIDE	authorization.JWTAudienceMapper <= go.temporal.io/server/temporal.ServerOptionsProvider()
>       [Fx] PROVIDE	log.Logger <= go.temporal.io/server/temporal.ServerOptionsProvider()
>       [Fx] PROVIDE	client.FactoryProvider <= go.temporal.io/server/temporal.ServerOptionsProvider()
>       [Fx] PROVIDE	dynamicconfig.Client <= go.temporal.io/server/temporal.ServerOptionsProvider()
>       [Fx] PROVIDE	*dynamicconfig.Collection <= go.temporal.io/server/temporal.ServerOptionsProvider()
>       [Fx] PROVIDE	encryption.TLSConfigProvider <= go.temporal.io/server/temporal.ServerOptionsProvider()
>       [Fx] PROVIDE	*client.Config <= go.temporal.io/server/temporal.ServerOptionsProvider()
>       [Fx] PROVIDE	client.Client <= go.temporal.io/server/temporal.ServerOptionsProvider()
>       [Fx] PROVIDE	metrics.Handler <= go.temporal.io/server/temporal.ServerOptionsProvider()
>       [Fx] PROVIDE	[]trace.SpanExporter <= go.temporal.io/server/temporal.glob..func2()
>       [Fx] PROVIDE	client.FactoryProviderFn <= go.temporal.io/server/temporal.PersistenceFactoryProvider()
>       [Fx] PROVIDE	*temporal.ServicesMetadata[group = "services"] <= go.temporal.io/server/temporal.HistoryServiceProvider()
>       [Fx] PROVIDE	*temporal.ServicesMetadata[group = "services"] <= go.temporal.io/server/temporal.MatchingServiceProvider()
>       [Fx] PROVIDE	*temporal.ServicesMetadata[group = "services"] <= go.temporal.io/server/temporal.FrontendServiceProvider()
>       [Fx] PROVIDE	*temporal.ServicesMetadata[group = "services"] <= go.temporal.io/server/temporal.InternalFrontendServiceProvider()
>       [Fx] PROVIDE	*temporal.ServicesMetadata[group = "services"] <= go.temporal.io/server/temporal.WorkerServiceProvider()
>       [Fx] PROVIDE	*cluster.Config <= go.temporal.io/server/temporal.ApplyClusterMetadataConfigProvider()
>       [Fx] PROVIDE	config.Persistence <= go.temporal.io/server/temporal.ApplyClusterMetadataConfigProvider()
>       [Fx] PROVIDE	fx.Lifecycle <= go.uber.org/fx.New.func1()
>       [Fx] PROVIDE	fx.Shutdowner <= go.uber.org/fx.(*App).shutdowner-fm()
>       [Fx] PROVIDE	fx.DotGraph <= go.uber.org/fx.(*App).dotGraph-fm()
>       [Fx] ERROR		Failed to initialize custom logger: could not build arguments for function "go.uber.org/fx".(*App).constructCustomLogger.func2
> 	      /go/pkg/mod/go.uber.org/fx@v1.18.2/app.go:414:
>       failed to build fxevent.Logger:
>       could not build arguments for function "go.temporal.io/server/temporal".glob..func8
> 	      /home/builder/temporal/temporal/fx.go:1013:
>       failed to build log.Logger:
>       received non-nil error from function "go.temporal.io/server/temporal".ServerOptionsProvider
> 	      /home/builder/temporal/temporal/fx.go:159:
>       **cassandra schema version compatibility check failed: no connections were made when creating the session
>       Unable to create server.** Error: could not build arguments for function "go.uber.org/fx".(*App).constructCustomLogger.func2 (/go/pkg/mod/go.uber.org/fx@v1.18.2/app.go:414): failed to build fxevent.Logger: could not build arguments for function "go.temporal.io/server/temporal".glob..func8 (/home/builder/temporal/temporal/fx.go:1013): failed to build log.Logger: received non-nil error from function "go.temporal.io/server/temporal".ServerOptionsProvider (/home/builder/temporal/temporal/fx.go:159): cassandra schema version compatibility check failed: no connections were made when creating the session

</details>

For frontend, history, matching services, the error log is identical
The deployment does not work both on our production cluster and in the test minikube.

I would greatly appreciate it if you could help me and find a way to fix this problem.

**Environment**:
Production - Kubernetes version: 1.29.1
Local - minikube v1.32.0 on Darwin 14.3.1 (arm64)

**Comment by alexandrevilain** [comment]
Hi @j0hnni3 ! 

Thanks for reporting this issue !

Are you using the cassandra server provided in the example ? 

After digging a bit it looks like a config issue: https://github.com/gocql/gocql/issues/946

**Comment by j0hnni3** [comment]
Hi @alexandrevilain 
I used both my own installation (k8ssandra) and the one [used in the operator](https://github.com/alexandrevilain/temporal-operator/blob/main/examples/cluster-cassandra/01-cassandra.yaml). The same issue

**Comment by alexandrevilain** [comment]
Hi @j0hnni3 !

I managed to reproduce and I think that I found the issue. E2e tests are working but not examples. 

By checking the diff it seems the issue is due to `disableInitialHostLookup: true` set here:
- https://github.com/alexandrevilain/temporal-operator/blob/main/examples/cluster-cassandra/02-temporal-cluster.yaml#L28
- https://github.com/alexandrevilain/temporal-operator/blob/main/examples/cluster-cassandra/02-temporal-cluster.yaml#L40

Everything was working as expected after applying the following diff to the `examples/cluster-cassandra/02-temporal-cluster.yaml` file:

```diff
diff --git a/examples/cluster-cassandra/02-temporal-cluster.yaml b/examples/cluster-cassandra/02-temporal-cluster.yaml
index 2d28a64..b6f61a8 100644
--- a/examples/cluster-cassandra/02-temporal-cluster.yaml
+++ b/examples/cluster-cassandra/02-temporal-cluster.yaml
@@ -25,7 +25,7 @@ spec:
         user: cassandra
         keyspace: temporal
         datacenter: datacenter1
-        disableInitialHostLookup: true
+        disableInitialHostLookup: false
       passwordSecretRef:
         name: cassandra-password
         key: PASSWORD
@@ -37,7 +37,7 @@ spec:
         user: cassandra
         keyspace: temporal_visibility
         datacenter: datacenter1
-        disableInitialHostLookup: true
+        disableInitialHostLookup: false
       passwordSecretRef:
         name: cassandra-password
         key: PASSWORD
```
