### ISSUE TITLE
Some TemporalNamespace reconciliation status conditions are never updated 

### ISSUE THREAD

**Issue by jashandeep-sohi** [alexandrevilain/temporal-operator#665]
While trying to debug why a `TemporalNamespace` was not deleting, I think I've hit a bug related to patching the `status.conditions` field:

This:
https://github.com/alexandrevilain/temporal-operator/blob/cf59d6864da23954335d72a8fc331a6b85f5f08f/controllers/temporalnamespace_controller.go#L80

Comes before the patch helper setup:
https://github.com/alexandrevilain/temporal-operator/blob/cf59d6864da23954335d72a8fc331a6b85f5f08f/controllers/temporalnamespace_controller.go#L89-L100

So it's never actually updated.

**Comment by alexandrevilain** [comment]
Hi! 

Thanks for reporting this issue! It will be fixed as soon as possible! 👌
