### ISSUE TITLE
E2E tests are not using the correct Kind version

### ISSUE THREAD

**Issue by jashandeep-sohi** [alexandrevilain/temporal-operator#675]
If you look at logs in any of the E2E artifacts, you'll notice all Kind cluster are `v1.27.1`.

This seems to be the default image for the version of Kind installed with the Github Action: https://github.com/kubernetes-sigs/kind/releases/tag/v0.19.0

Issue stems from the fact that the e2e-framework API is misleading. It never takes the Provider image options into account when launching Kind: https://github.com/kubernetes-sigs/e2e-framework/blob/fdcf509f96c96f0055b03f026ea44c62df82c753/support/kind/kind.go#L170

**Comment by alexandrevilain** [comment]
Closing as #676 has been merged
