### ISSUE TITLE
Not able to deploy version: 1.23.0 

### ISSUE THREAD

**Issue by manojkumargogula** [alexandrevilain/temporal-operator#696]

**Comment by alexandrevilain** [comment]
Hi @manojkumargogula !
Could you please add some context ? maybe some logs ?

**Comment by manojkumargogula** [comment]
@alexandrevilain  here are the logs when installing version: 1.23.0

apiVersion: temporal.io/v1beta1
kind: TemporalCluster
metadata:
  name: prod
  namespace: demo
spec:
  version: 1.23.0
  numHistoryShards: 1
  persistence:
    defaultStore:
      sql:
        user: temporal
        pluginName: mysql
        databaseName: temporal
        connectAddr: mysql.demo.svc.cluster.local:3306
        connectProtocol: tcp
      passwordSecretRef:
        name: mysql-password
        key: PASSWORD
    visibilityStore:
      sql:
        user: temporal
        pluginName: mysql
        databaseName: temporal_visibility
        connectAddr: mysql.demo.svc.cluster.local:3306
        connectProtocol: tcp
      passwordSecretRef:
        name: mysql-password
        key: PASSWORD
  ui:
    enabled: true
  admintools:
    enabled: true
  metrics:
    enabled: false

**Comment by alexandrevilain** [comment]
Which version of the operator are you using ? 
If 0.17.0, please wait for 0.18.0. It will be released soon ;)

**Comment by manojkumargogula** [comment]
@alexandrevilain  thanks for the information
