### ISSUE TITLE
httpPort in the service spec being ignored

### ISSUE THREAD

**Issue by guritinvda** [alexandrevilain/temporal-operator#703]
`httpPort` field in the service spec [[ref](https://github.com/alexandrevilain/temporal-operator/blob/c9e7054e2f8724017953007cdc7687442d9e1f6d/docs/api/v1beta1.md#servicespec)] seems to be getting ignored. It looks like the purpose of this field is to expose the REST API. I can confirm that the REST API is in fact accessible from within the pod. The port simply needs to be exposed by the operator.

**Comment by alexandrevilain** [comment]
Hi @guritinvda ! 

Thanks for reporting this, looks like this is missing in the frontend service.

@yujunz how are you using the http port without exposing it on the service ?

**Comment by guritinvda** [comment]
@alexandrevilain we are not using it. So, this is not a big deal for us. Just wanted to report that the field is exposed; implying that it will expose the port and hence the REST API will be accessible.

**Comment by alexandrevilain** [comment]
Thanks for the report!
