### ISSUE TITLE
Invalid subject name being set as it does not match hostname.

### ISSUE THREAD

**Issue by ElanHasson** [alexandrevilain/temporal-operator#707]
If you look here at how the `dnsName` is set:
https://github.com/alexandrevilain/temporal-operator/blob/ccb4cf841e6e43adb253e7f831f0f2b28c42716d/pkg/resource/certmanager/mtls_frontend_certificate_builder.go#L53

and then at how the name is generated:

https://github.com/alexandrevilain/temporal-operator/blob/6deb001777cef384460ad113b4db433b1885af3e/api/v1beta1/temporalcluster_types.go#L610

You'll see it generates a `dnsName` like this: `frontend.$clusterName.$namespace.svc.cluster.local` which is incorrect-- the server name should not be part of the name. 

If this is needed for some reason, there should be support for adding additional SANs/DNS Names to the certificate for generation.

Of course, I could be missing something here..

**Comment by ElanHasson** [comment]
btw, the workaround here was to use SNI in my client apps

**Comment by alexandrevilain** [comment]
Hi @ElanHasson !

Sorry but I don't get the point, what's wrong with the current code ? 
What are you expecting ? 

Thanks :)

**Comment by alexandrevilain** [comment]
Oh you mean `$clusterName` should not be part of the dnsName ?

**Comment by ElanHasson** [comment]
Correct!

The DNS name in the cert does not match the actual hostname.

The following should be in the cert at a minimum 
-  pod name
-  fqdn of the service


For those who want to terminate tls at the pod vs ingress / lb: the ability to define the set for DNS name, I.e excluding pod name / fqdn of the svc

**Comment by alexandrevilain** [comment]
Hi @ElanHasson !

Thanks. 
No issue with the `fqdn of the service` looks like a bug, so I'll fix it. 

But pod name would require extra work, what's the use case ?

**Comment by ElanHasson** [comment]
Thank you.

@alexandrevilain 

I am referring to the fqdn.

I guess it's not pod name but the service.

One should be able to use mtls without requiring SNI.

**Comment by ElanHasson** [comment]
Thanks @alexandrevilain !
