### ISSUE TITLE
Temporal UI should not run as root

### ISSUE THREAD

**Issue by arunsworld** [alexandrevilain/temporal-operator#730]
The process within the Temporal UI container (ui-server) is running as root which isn't secure.

Current image (temporalio/ui) provides support for a temporal user.

By adding this reference to the securityContext this issue can be resolved.

Have the fix working locally. Happy to submit PR.

**Comment by alexandrevilain** [comment]
Hi @arunsworld !

Oh that's a bad news :( I didn't see that. I'll be happy to review your PR fixing this :)
