### ISSUE TITLE
Images being pulled every time leading to timeouts and slowdowns

### ISSUE THREAD

**Issue by arunsworld** [alexandrevilain/temporal-operator#731]
The image policy for tools and other images is set to be pulled Always rather than IfNotPresent.

This causes the image (particularly the admin one) to be repeatedly pulled during cluster setup. Leads to slowdowns due to timeouts despite the image being available.

Not seeing any downside to changing to IfNotPresent which is quite common practice.

Have the change working locally and happy to submit PR.

**Comment by alexandrevilain** [comment]
Hi @arunsworld !

Nice catch, feel free to open a PR :)
