### ISSUE TITLE
CRD object status is not being updated after reconciliation

### ISSUE THREAD

**Issue by AdamSendible** [alexandrevilain/temporal-operator#737]
## Summary

Controller reconciliation for Temporal namespace are not patching/applying the object `status.conditions` updates on first reconciliation of a new Temporal namespace object. 

## Steps to Reproduce

1. Add a new `TemporalNamespace` to the cluster
2. Reconciliation is successful
3. `TemporalNamespace.status.conditions` are still empty.
4. Update the `TemporalNamespace` object
5. Reconciliation now correctly patches the object's `status.conditions`

## Expected Results

The controller should patch/apply the `status.conditions` updates to the object on every reconciliation run.

## Actual Results

The `status.conditions` updates are not patched/applied after initial reconciliation. The updates are, however, applied after a secondary reconciliation is run.

**Comment by alexandrevilain** [comment]
Hi @AdamSendible !

Thanks for reporting this issue. It may be related to an issue in https://github.com/alexandrevilain/controller-tools/tree/main/pkg/patch where I'm having issues to upgrade the Kubernetes client.

I'll take a look as soon as possible.

**Comment by alexandrevilain** [comment]
Ok I found the issue, it will be fixed in https://github.com/alexandrevilain/controller-tools/pull/111 once I ci is fixed :)
