### ISSUE TITLE
Operator does not have permissions to delete configmaps

### ISSUE THREAD

**Issue by AdamSendible** [alexandrevilain/temporal-operator#738]
## Summary

The operator lacks the necessary permissions to delete ConfigMaps, particularly when attempting to remove `TemporalCluster.spec.dynamicConfig`.

## Description

Upon attempting to delete ConfigMaps in the context of managing `TemporalCluster.spec.dynamicConfig`, an error is encountered indicating insufficient permissions. This inhibits the operator's functionality and disrupts the intended system operations.

## Steps to Reproduce

1. Add a `dynamicConfig` to cluster spec
2. Remove `TemporalCluster.spec.dynamicConfig` using the operator.
2. Observe the error in TemporalCluster reconciliation indicating permission denial.

## Expected Behavior

The operator should have the necessary permissions to delete ConfigMaps related to `TemporalCluster.spec.dynamicConfig` without encountering permission-related errors.

## Actual Behavior

The operator fails to delete ConfigMaps and prevents cluster reconciliation.

## Environment

- **Operator Version**: [v0.18.0](https://github.com/alexandrevilain/temporal-operator/releases/tag/v0.18.0)

## Additional Information

TemporalCluster reconciliation error:
```
can't delete resource: configmaps "active-dynamicconfig" is forbidden: User "system:serviceaccount:temporal-system:temporal-operator-controller-manager" cannot delete resource "configmaps" in API group "" in the namespace "temporal"
```

**Comment by alexandrevilain** [comment]
Hi @AdamSendible ! Thanks for reporting this issue, this will be fixed in #739
