### ISSUE TITLE
no entry in compatability matrix for temporal-operator v0.19.0

### ISSUE THREAD

**Issue by TheHiddenLayer** [alexandrevilain/temporal-operator#772]
I don't see a compatability row for the latest operator version. Am I missing something? 

EDIT: I notice on the [compatability matrix](https://github.com/alexandrevilain/temporal-operator?tab=readme-ov-file#compatibility-matrix)

> Please note this table only reports end-to-end tests suite coverage, others versions may work.

So, I'm assuming that end-to-end test suites haven't been run on **v0.19.0**

**Comment by alexandrevilain** [comment]
Hi! 
Thanks for reporting this issue. 
This will be fixed in: https://github.com/alexandrevilain/temporal-operator/pull/760/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

**Comment by TheHiddenLayer** [comment]
thanks for fixing this @alexandrevilain !
