### ISSUE TITLE
Update schema job failed with Yugabyte CQL

### ISSUE THREAD

**Issue by sotatek-hungpham5** [alexandrevilain/temporal-operator#792]
The create and setup schema job successfully but I see the update job failed with this error:

```
CREATE TYPE serialized_event_batch ( encoding_type text, version int, data blob );    {"logging-call-at": "updatetask.go:154"}
ERROR    Unable to update CQL schema.    {"error": "error executing statement:Duplicate Type. Type 'temporal_hung.serialized_event_batch' already exists (master error 19)\nCREATE TYPE serialized_event_batch
```

It seems like missing IF NOT EXISTS in CQL script

**Comment by alexandrevilain** [comment]
Hi @sotatek-hungpham5 !

Thanks for reporting this issue.
Unfortunately the issue is not on the operator side because it uses "official" database migration tools. 

Looks like it's not supported on temporal for now: https://github.com/temporalio/temporal/issues/3511
