### ISSUE TITLE
Add support for temporal 1.25

### ISSUE THREAD

**Issue by nerdingassendible** [alexandrevilain/temporal-operator#806]
Temporal has released 1.25 couple of weeks ago and it would be great if this operator supported it.

**Comment by alexandrevilain** [comment]
Hi @nerdingassendible !

Thanks for the issue! You're right.

I'm currently working on v1.24 support, I have issues finding free time to get it done :) But it's in my top priorities.

Feel free to contribute!

**Comment by alexandrevilain** [comment]
Hi @nerdingassendible ! 

Support for v1.24 has been merged and is now released in 0.20.0.

Support for v1.25 is now ongoing.
