### ISSUE TITLE
Unable to create SQL database.

### ISSUE THREAD

**Issue by s123121** [alexandrevilain/temporal-operator#813]
Using the getting start template, I encounter this error:
```
Unable to create SQL database.    {"error": "plugin not supported: unknown plugin \"postgres\", supported plugins: [mysql8 postgres12 postgres12_pgx sqlite]", "logging-call-at": "handler.go:94"}
```

Downgrade to 1.23.0 worked

EDIT: also `api/v1beta1/temporalcluster_defaults.go` seems lack of admin-tools version

**Comment by alexandrevilain** [comment]
For the admin-tools version this is now fixed https://github.com/alexandrevilain/temporal-operator/pull/825 and will be available in the next release.
