### ISSUE TITLE
v1beta1 API and GroupVersionKind update

### ISSUE THREAD

**Issue by alexandrevilain** [alexandrevilain/temporal-operator#82]
This issue is here to open discussion about API changes before going to v1.0.0

## API

The current state of the operator's API:
- apps.alexandrevilain.dev/v1alpha1.TemporalCluster
- apps.alexandrevilain.dev/v1alpha1.TemporalClusterClient
- apps.alexandrevilain.dev/v1alpha1.TemporalNamespace

I find the `Temporal` prefix for each CRDs redoundant.
Maybe we can rename them to:
- temporal.alexandrevilain.dev/v1beta1.Cluster
- temporal.alexandrevilain.dev/v1beta1.Client
- temporal.alexandrevilain.dev/v1beta1.Namespace

The `v1beta1` API version can be the starting point to declare the API stable and stop making breaking changes to it.

## Webhooks

The `v1beta1` can also be the first API with defaulting and validating webhooks.

As webhooks need certificates two solutions are available:
- Asking the user to install the operator alongside cert-manager
- Using [cert-controller](https://github.com/open-policy-agent/cert-controller)

## Any thoughts

I would be happy to get any feedbacks about this idea.🙂

**Comment by ktenzer** [comment]
Yeah that would be actually great and I agree we should refactor the spec
before changing API endpoint of CRD. In fact this already bit me once in
the CSV :) I just submitted pull request for API endpoint change. Should I
close it and resubmit later after this is refactored? I don't think
changing API endpoint matters much either way more of when you want to do
that change.

**Comment by alexandrevilain** [comment]
Hi @ktenzer 

https://github.com/alexandrevilain/temporal-operator/pull/130 and https://github.com/alexandrevilain/temporal-operator/pull/132 have been merged! I think we're almost ready to close this issue and release 0.7.0 :)

**Comment by ktenzer** [comment]
After using new API I think we should change the CRDs 
from:
Cluster
Namespace
ClusterClient

To:
TemporalCluster
TemporalNamespace
TemporalClusterClient

The reason is user experience. Namespace clashes so user has to set namespace.temporal.io. In addition cluster is just really generic and likely could class with other operators. Finally just having Temporal in front of it I think makes it consistent.

**Comment by alexandrevilain** [comment]
After writing some `kubectl` I really agree with your idea.
I'll have the time to do that this week-end. 
Then once this fix is done and once your PR is merged, I'll release v0.7.0 :)

**Comment by alexandrevilain** [comment]
We can close as release v0.7.0 ships with the new GVK :)
