### ISSUE TITLE
Unable to bootstrap ringpop / configurable maxJoinDuration

### ISSUE THREAD

**Issue by dave-ledgy** [alexandrevilain/temporal-operator#824]
Hi, many thanks for the operator. I've been getting issues with not being able to bootstrap ringpop in time and was wondering if it would be possible to make the maxJoinDuration configurable? It appears to be hardcoded at 30 seconds currently, and my cluster doesn't seem to be able to bootstrap in that timeframe. For context, the following error is received: `exhausted all retries: join duration of 44.89636036s exceeded max 30s`. Many thanks!

**Comment by alexandrevilain** [comment]
Hi! @dave-ledgy !

Maybe we can provide ringpop configuration in the API. 
But don't you think that 30s is enough in most of the cases, don't you have any network issue ?
