### ISSUE TITLE
Upgrading controller

### ISSUE THREAD

**Issue by smolinari** [alexandrevilain/temporal-operator#833]
Hi,

Not sure I'm doing this right, but when I "reinstalled" the controller to the latest version and changed the cluster to version 1.24.2, the update-default-schema job is failing with 

> Oops. I thought I copied the error message.....

I'm just experimenting for now, so I'll be deleting the cluster and trying a new install.  I'll report back on how that works. 

Scott

**Comment by smolinari** [comment]
Darnit. I didn't copy the error message. So, this can be deleted/ignored. 

Scott

**Comment by smolinari** [comment]
In the en

**Comment by smolinari** [comment]
Ok. I have the original error I wanted to report. I changed the version in the cluster-values.yaml to 1.24.2 and this is what I'm seeing.
```
ERROR	Unable to create SQL database.	{"error": "plugin not supported: unknown plugin \"postgres\", supported plugins: [mysql8 postgres12 postgres12_pgx sqlite]", "logging-call-at": "handler.go:94"}
```

Now going to try 1.23.2 again.

**Comment by s123121** [comment]
check https://github.com/alexandrevilain/temporal-operator/issues/813

Maybe will update soon

**Comment by geoffreytran** [comment]
https://github.com/alexandrevilain/temporal-operator/pull/831

Appears to be the issue upgrading from 1.23 -> 1.24

**Comment by smolinari** [comment]
Yup. Closing this for that one. 

Scott

**Comment by smolinari** [comment]
For anyone landing here. To fix the upgrade issue of:

> ERROR	Unable to create SQL database.	{"error": "plugin not supported: unknown plugin \"postgres\", supported plugins: [mysql8 postgres12 postgres12_pgx sqlite]", "logging-call-at": "handler.go:94"}

Change the plugin value under  `spec.persistance.defaultStore.pluginName` and `spec.persistance.visibilityStore.pluginName` in `cluster-values.yaml` to `postgres12`.

Scott
