### ISSUE TITLE
Add Helm option to use webhook with host network

### ISSUE THREAD

**Issue by ttretau** [alexandrevilain/temporal-operator#847]
While deploying with the Helm chart to an AWS managed EKS cluster, I noticed that the webhook needs to be adapted to the host network.
This makes the admission webhooks work.

I have prepared a PR to add this option.

**Comment by alexandrevilain** [comment]
Hi @ttretau !
Thanks for the issue and the PR. 

Could you please link me any documentation in AWS that explains why this is required ? Thanks.

**Comment by ttretau** [comment]
Hi @alexandrevilain,

sure, here is a [link to the AWS docs](https://docs.aws.amazon.com/eks/latest/best-practices/custom-networking.html) and even better explanations that describe the situation:

https://medium.com/@denisstortisilva/kubernetes-eks-calico-and-custom-admission-webhooks-a2956b49bd0d
https://cert-manager.io/docs/installation/compatibility/#aws-eks

**Comment by alexandrevilain** [comment]
Thanks @ttretau !
Let's merge this.
